version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: sgpc_mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: sgpc_db
      MYSQL_ROOT_PASSWORD: password123
    ports:
      - "3306:3306"
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  api:
    build: ./backend
    container_name: sgpc_api
    restart: always
    ports:
      - "3001:3001"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: password123
      DB_NAME: sgpc_db
      JWT_SECRET: sgpc_contraloria_uv_secreto_2026
      JWT_EXPIRES_IN: 8h
      PORT: 3001
      # Configuración de Servidor de Correos (SMTP)
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 587
      SMTP_USER: sgpcontraloria@gmail.com
      SMTP_PASS: asvh eifx ndsa mnmu
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: sgpc_frontend
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - api